# This is a basic workflow to help you get started with Actions

name: NextDNS container

# Controls when the action will run. 
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
     - nextdns/docker/Dockerfile
  schedule:
    - cron: "0 0 */15 * *"
  

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set the version
        id: set_version
        run: |
          echo VERSION=$(curl --silent "https://api.github.com/repos/nextdns/nextdns/releases/latest" | jq -r '.["tag_name"]')>> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      -
        name: build pihole $VERSION
        run: docker buildx build --platform=linux/amd64,linux/arm64 --build-arg VERSION=${{ env.VERSION }} nextdns/docker -t boostchicken/nextdns:latest -t boostchicken/nextdns:${{ env.VERSION }} --push
